#!/bin/bash
#
#一键部署脚本

WAR_PATH="/home/wcy/project/learnspring/app/target/app.jar"
DEPLOY_PATH="/home/wcy/app/app.jar"

cd /home/wcy/project/learnspring/

printf "> 正在更新代码...\n"
git pull

printf "> 正在清理...\n"
mvn clean

printf "> 正在打包...\n"
mvn package

if [ -f $WAR_PATH ];
then
    printf "> 打包成功...\n"
    cp -rf $WAR_PATH $DEPLOY_PATH
    printf "> 拷贝成功...\n"
    nohup java -jar $DEPLOY_PATH
else
    printf "> 打包失败...\n"
fi