#!/bin/bash
#
#一键部署脚本

WAR_PATH="/home/wcy/projects/learnspring/app/target/app.war"
DEPLOY_PATH="/home/wcy/apache-tomcat-7.0.81/webapps/app.war"

cd /home/wcy/projects/learnspring/

printf "> 正在更新代码...\n"
git pull

printf "> 正在清理...\n"
mvn clean

printf "> 正在打包...\n"
mvn package

if [ -f $WAR_PATH ];
then
    printf "> 打包成功...\n"
    cp -rf $WAR_PATH $DEPLOY_PATH
    printf "> 拷贝成功...\n"
else
    printf "> 打包失败...\n"
fi